spring.application.name=habit-tracker

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/habit_tracker?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:habit_tracker}
spring.datasource.password=${DB_PASSWORD:habit_tracker}
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true

server.port=${SERVER_PORT:8080}
